import DesktopNav from "@/components/DesktopNav";
import Header from "@/components/Header";
import { theme } from "@/theme";
import { Center, UIProvider, VStack } from "@yamada-ui/react";
import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import { ReactNode } from "react";

const ZenKakuGothicNewFont = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="jp">
      <body className={ZenKakuGothicNewFont.className}>
        <UIProvider theme={theme}>
          <VStack minH="100vh">
            <DesktopNav />
            <VStack px={{ base: "2xl", sm: "xs" }} minH="100vh">
              <Header />
              <Center as="main" w="full">
                <VStack
                  w="full"
                  gap={{ base: "lg", md: "md" }}
                  py="lg"
                  px={{ base: "lg", md: "md" }}
                  maxW="9xl"
                  alignItems="center"
                >
                  {children}
                </VStack>
              </Center>
            </VStack>
          </VStack>
        </UIProvider>
      </body>
    </html>
  );
}
